service: notes-api

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
